# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX_BASE = "ubuntu/trusty64"
BOX_CPU_COUNT = "1" 
BOX_EXEC_CAP = "90"
BOX_RAM_MB = "1024"


Vagrant.configure("2") do |config|
  # Base box, ubuntu 64 bit
  config.vm.box = BOX_BASE
  # provider configs  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = BOX_RAM_MB
    vb.cpus = BOX_CPU_COUNT
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", BOX_EXEC_CAP]
  end

  #Synced folder
  config.vm.synced_folder ".", "/home/vagrant"

  config.vm.provision "shell", path: "../setup.sh"

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
end
